### PR TITLE
Create a separate snapctl package

### PR DESCRIPTION
**Pull request by farshidtz**
To Do:
- [x] get
- [x] set
- [x] unset
- [ ] start
- [ ] stop
- [x] services
- [ ] restart

### CODE REVIEW

**Comment by farshidtz** [comment]
Let's review and get this merged to have the testing environment and the new function for use by other parallel work. The remaining tasks can be done in separate PRs.

**Comment by farshidtz** [comment]
@siggiskulason I've added the `set` functions.

**Comment by farshidtz** [comment]
@siggiskulason I've implemented the services functions needed for the new config options API.

**Review by siggiskulason — APPROVED** [review]
LGTM. Tested this according to the instructions and everything ran as expected. The code looks good as well, but as this is still a work in progress I won't do a code review until it's all done.

**Pull request merged**
