### PR TITLE
Extend copy directory tests

### PR DESCRIPTION
**Pull request by farshidtz**
Extending tests added in #59

### CODE REVIEW

**Review by MonicaisHer — APPROVED** [review]
@farshidtz Thanks for the changes.

**Comment by MonicaisHer** [comment]
```
make try

snap try prime
error: cannot try /home/mengyi/Desktop/codereview/edgex-snap-hooks/prime: snap
       is unusable due to bad permissions; contact developer
make: *** [Makefile:4: try] Error 1
```

**Comment by farshidtz** [comment]
> ```
> SNAPCRAFT_BUILD_ENVIRONMENT=lxd make try
> 
> snap try prime
> error: cannot try /home/mengyi/Desktop/codereview/edgex-snap-hooks/prime: snap
>        is unusable due to bad permissions; contact developer
> make: *** [Makefile:4: try] Error 1
> ```

Try
```
snap remove edgex-snap-hooks
rm -r prime
SNAPCRAFT_BUILD_ENVIRONMENT=lxd snapcraft clean
SNAPCRAFT_BUILD_ENVIRONMENT=lxd make try
```

**Comment by MonicaisHer** [comment]
> > ```
> > SNAPCRAFT_BUILD_ENVIRONMENT=lxd make try
> > 
> > snap try prime
> > error: cannot try /home/mengyi/Desktop/codereview/edgex-snap-hooks/prime: snap
> >        is unusable due to bad permissions; contact developer
> > make: *** [Makefile:4: try] Error 1
> > ```
> 
> Try
> 
> ```
> snap remove edgex-snap-hooks
> rm -r prime
> SNAPCRAFT_BUILD_ENVIRONMENT=lxd snapcraft clean
> SNAPCRAFT_BUILD_ENVIRONMENT=lxd make try
> ```

Thanks, it works.

**Pull request merged**
