### PR TITLE
Override env file after processing all keys

### LINKED ISSUE #47: Setting a bad app key removed other keys from env file
```
$ snap set edgex-app-service-configurable config.service-startupmsg="testing injection"
$ snap set edgex-app-service-configurable apps.app-service-configurable.config.service-port=11111
$ cat /var/snap/edgex-app-service-configurable/current/config/res/app-service-configurable.env 
export SERVICE_STARTUPMSG="testing injection"
export SERVICE_PORT="11111"

$ snap set edgex-app-service-configurable apps.app-service-configurable.config.service.port=11111
error: cannot perform the following tasks:
- Run configure hook of "edgex-app-service-configurable" snap (run hook "configure": edgex-app-service-configurable.configure: could not process options: error converting config key to environment variable key: config key must not contain dots: service.port)
$ cat /var/snap/edgex-app-service-configurable/current/config/res/app-service-configurable.env 
export SERVICE_STARTUPMSG="testing injection"
```

### LINKED ISSUE #53: Env files not removed after disabling app options
The env files created for app options, are not removed after disabling app options. They will get replaced however as soon an an env option is set.

### PR DESCRIPTION
**Pull request by farshidtz**
Fixes #47 
Fixes #53

### CODE REVIEW

**Comment by farshidtz** [comment]
I've ran the device-mqtt tests against this and they all pass.

To test the edgexfoundry snap:
- Make sure migration from env to apps for proxy happens
- Run the tests
- Verify that https://github.com/canonical/edgex-snap-hooks/issues/47 is fixed
- Make sure disabling app options will empty the env files

**Comment by MonicaisHer** [comment]
Migration from env to apps for proxy doesn't happen:
```
$ sudo snap get edgexfoundry -d
{
	"env": {
		"security-bootstrapper": {
			"add-registry-acl-roles": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
		},
		"security-proxy": {
			"public-key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1yN3qVSWAjbVy2UTTbTW0gHehUxd\njkxPIBxKDdziCwCJP9agP78/WXgGajY/dqIVZZqYZIJeC3ZlU16wsU9biA==\n-----END PUBLIC KEY-----",
			"user": "user01,USER_ID,ES256"
		},
		"security-secret-store": {
			"add-known-secrets": "redisdb[app-functional-tests],redisdb[app-rules-engine],redisdb[app-http-export],redisdb[app-mqtt-export],redisdb[app-external-mqtt-trigger],redisdb[app-push-to-core],redisdb[app-rfid-llrp-inventory],redisdb[application-service],redisdb[device-rest],redisdb[device-virtual],redisdb[device-camera],redisdb[device-mqtt],redisdb[device-modbus],redisdb[device-coap],redisdb[device-snmp],redisdb[device-gpio],redisdb[device-bacnet],redisdb[device-grove],redisdb[device-uart],redisdb[device-rfid-llrp],redisdb[edgex-ekuiper]",
			"add-secretstore-tokens": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
		}
	}
}
$ sudo snap set edgexfoundry app-options=true
$ sudo snap get edgexfoundry -d
{
	"app-options": true,
	"apps": {
		"security-bootstrapper": {
			"config": {
				"add-registry-acl-roles": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
			}
		},
		"security-secretstore-setup": {
			"config": {
				"add-known-secrets": "redisdb[app-functional-tests],redisdb[app-rules-engine],redisdb[app-http-export],redisdb[app-mqtt-export],redisdb[app-external-mqtt-trigger],redisdb[app-push-to-core],redisdb[app-rfid-llrp-inventory],redisdb[application-service],redisdb[device-rest],redisdb[device-virtual],redisdb[device-camera],redisdb[device-mqtt],redisdb[device-modbus],redisdb[device-coap],redisdb[device-snmp],redisdb[device-gpio],redisdb[device-bacnet],redisdb[device-grove],redisdb[device-uart],redisdb[device-rfid-llrp],redisdb[edgex-ekuiper]",
				"add-secretstore-tokens": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
			}
		}
	}
}
```

**Comment by MonicaisHer** [comment]
After enabling app-options, it is not possible to disable it:
```
$ sudo snap set edgexfoundry app-options=true
$ sudo snap unset edgexfoundry app-options
error: cannot perform the following tasks:
- Run configure hook of "edgexfoundry" snap (run hook "configure": 
-----
edgexfoundry: edgexfoundry:configure could not process config options: app options (prefix `apps.' or 'config.') are allowed only when app-options is true.

WARNING: Setting app-options=true will unset existing env options and ignore future sets!!
Exception: The following legacy env options are automatically converted:
	- env.security-secret-store.add-secretstore-tokens
	- env.security-secret-store.add-known-secrets
	- env.security-bootstrapper.add-registry-acl-roles
-----)
```

**Comment by farshidtz** [comment]
> Migration from env to apps for proxy doesn't happen:
> 
> ```
> $ sudo snap get edgexfoundry -d
> {
> 	"env": {
> 		"security-bootstrapper": {
> 			"add-registry-acl-roles": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
> 		},
> 		"security-proxy": {
> 			"public-key": "-----BEGIN PUBLIC KEY-----\nMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE1yN3qVSWAjbVy2UTTbTW0gHehUxd\njkxPIBxKDdziCwCJP9agP78/WXgGajY/dqIVZZqYZIJeC3ZlU16wsU9biA==\n-----END PUBLIC KEY-----",
> 			"user": "user01,USER_ID,ES256"
> 		},
> 		"security-secret-store": {
> 			"add-known-secrets": "redisdb[app-functional-tests],redisdb[app-rules-engine],redisdb[app-http-export],redisdb[app-mqtt-export],redisdb[app-external-mqtt-trigger],redisdb[app-push-to-core],redisdb[app-rfid-llrp-inventory],redisdb[application-service],redisdb[device-rest],redisdb[device-virtual],redisdb[device-camera],redisdb[device-mqtt],redisdb[device-modbus],redisdb[device-coap],redisdb[device-snmp],redisdb[device-gpio],redisdb[device-bacnet],redisdb[device-grove],redisdb[device-uart],redisdb[device-rfid-llrp],redisdb[edgex-ekuiper]",
> 			"add-secretstore-tokens": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
> 		}
> 	}
> }
> $ sudo snap set edgexfoundry app-options=true
> $ sudo snap get edgexfoundry -d
> {
> 	"app-options": true,
> 	"apps": {
> 		"security-bootstrapper": {
> 			"config": {
> 				"add-registry-acl-roles": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
> 			}
> 		},
> 		"security-secretstore-setup": {
> 			"config": {
> 				"add-known-secrets": "redisdb[app-functional-tests],redisdb[app-rules-engine],redisdb[app-http-export],redisdb[app-mqtt-export],redisdb[app-external-mqtt-trigger],redisdb[app-push-to-core],redisdb[app-rfid-llrp-inventory],redisdb[application-service],redisdb[device-rest],redisdb[device-virtual],redisdb[device-camera],redisdb[device-mqtt],redisdb[device-modbus],redisdb[device-coap],redisdb[device-snmp],redisdb[device-gpio],redisdb[device-bacnet],redisdb[device-grove],redisdb[device-uart],redisdb[device-rfid-llrp],redisdb[edgex-ekuiper]",
> 				"add-secretstore-tokens": "app-functional-tests,app-rules-engine,app-http-export,app-mqtt-export,app-external-mqtt-trigger,app-push-to-core,app-rfid-llrp-inventory,application-service,device-camera,device-mqtt,device-modbus,device-coap,device-snmp,device-gpio,device-bacnet,device-grove,device-uart,device-rfid-llrp,edgex-ekuiper"
> 			}
> 		}
> 	}
> }
> ```

We only migrate options that are set internally by the configure hook, not those set by users.

**Comment by farshidtz** [comment]
> After enabling app-options, it is not possible to disable it:
> 
> ```
> $ sudo snap set edgexfoundry app-options=true
> $ sudo snap unset edgexfoundry app-options
> error: cannot perform the following tasks:
> - Run configure hook of "edgexfoundry" snap (run hook "configure": 
> -----
> edgexfoundry: edgexfoundry:configure could not process config options: app options (prefix `apps.' or 'config.') are allowed only when app-options is true.
> 
> WARNING: Setting app-options=true will unset existing env options and ignore future sets!!
> Exception: The following legacy env options are automatically converted:
> 	- env.security-secret-store.add-secretstore-tokens
> 	- env.security-secret-store.add-known-secrets
> 	- env.security-bootstrapper.add-registry-acl-roles
> -----)
> ```

The migration removes three env options and sets them as app options. We don't have an implementation to revert that nor do we claim to support it.
To disable, you first need to manually unset apps and set the corresponding env options. This is because "app options (prefix `apps.' or 'config.') are allowed only when app-options is true".

We could improve the error message and make it clear that setting to false does not revert the migration.

**Review by MonicaisHer — APPROVED** [review]

**Pull request merged**
